### ISSUE TITLE
Release v0.2

### ISSUE THREAD

**Issue by s1fr0** [vacp2p/zerokit#100]
With this issue we scope out from the [zerokit development planning](https://github.com/vacp2p/zerokit/issues/91) the features and issues we want to address in next zerokit release v0.2. 

Reported items may change according to any eventual blocker found or re-prioritization of items. 

# List of items

## General
- [x] Check license compatibility with dependencies and add a license:
  - https://github.com/vacp2p/zerokit/issues/97
- [x] Add Makefile for zerokit workspace and for each package:
  - https://github.com/vacp2p/zerokit/issues/41
- [x] Separate tests from logic: 
  - https://github.com/vacp2p/zerokit/issues/98 

## `rln`
- [x] Code refactoring/optimization/clean-up (chores, todos, `clippy`, revise serialization, etc.):
  - https://github.com/vacp2p/zerokit/issues/96
- [x] Complete documentation of the modules (`ffi`, `protocol`, `utils`, etc.):
  - https://github.com/vacp2p/zerokit/issues/69
- [x] Audit FFI (in particular usage of `not_unsafe_ptr_arg_deref`):
   - https://github.com/vacp2p/zerokit/issues/96 (item)

## `rln-wasm`
- [x] Ensure all `rln` module public APIs are exposed by `rln-wasm`:
  - https://github.com/vacp2p/zerokit/issues/64

# Deadline
Completion of the above items is tracked in the the [Release v0.2](https://github.com/vacp2p/zerokit/milestone/1) milestone. 

A tentative deadline is set to 15 February 2023.

# Acceptance criteria
- [x] Address above items;
- [x] Update changelog and release.

**Comment by rymnc** [comment]
We're in a good state to release right now. We'll have to split the rln docs issue into two, one for the public api, and the docs (which is complete).

The nightly release would have the full changelog that we can include.

**Comment by rymnc** [comment]
I'll review it today

**Comment by rymnc** [comment]
Release has been created - https://github.com/vacp2p/zerokit/releases/tag/v0.2
