### ISSUE TITLE
Bump ark-circom to b892c62

### ISSUE THREAD

**Issue by rymnc** [vacp2p/zerokit#131]
## Background
ark-circom's latest version https://github.com/gakonst/ark-circom/commit/b892c62597687c23341cda1e8e89d58bb6428f36 includes arkworks 0.4.0, which has broken our CI, ref: https://github.com/vacp2p/zerokit/actions/runs/4463841234/jobs/7839439039

## Acceptance Criteria
- [ ] Investigate and bump accordingly

**Comment by tyshko-rostyslav** [comment]
This is done here: https://github.com/vacp2p/zerokit/pull/132
