### ISSUE TITLE
RLN: ark-circom CircomBuilder loads circuit resources slowly

### ISSUE THREAD

**Issue by s1fr0** [vacp2p/zerokit#23]
# Problem 

In zerokit RLN, [CircomBuilder](https://github.com/vacp2p/zerokit/blob/9cc333811b0a44638fe5ea5ac26a11f91a15aa68/rln/src/circuit.rs#L66-L75) from [ark-circom](https://github.com/gakonst/ark-circom) library is used to load the corresponding `.wasm` and `.r1cs` circuit files. 

This process may take up to 2-3 minutes at every RLN instance creation (witness generation and zk proof verification times are not affected)

# Acceptance criteria
- [x] Find out if this is expected behavior;
- [x] Minimize as much as possible loading time for circuit resources within ark-circom;
- [ ] If loading time are still not practical, implement alternative circuit loading mechanisms.

**Comment by oskarth** [comment]
Are you and @richard-ramos both looking into this? Probably good to make sure there isn't overlap here

**Comment by s1fr0** [comment]
It seems that compiling in `release` mode hugely improves performances. However, a better circuit logic, like the one implemented in https://github.com/vacp2p/zerokit/pull/26, further improves proof generation times.

**Comment by s1fr0** [comment]
Issue resolved in https://github.com/vacp2p/zerokit/pull/26
