### ISSUE TITLE
RLN: use space-efficient Merkle Tree implementation

### ISSUE THREAD

**Issue by s1fr0** [vacp2p/zerokit#29]
# Problem
[Currently](https://github.com/vacp2p/zerokit/commit/cbb10efc10adc4ae8d654c59e86740161669bd80), zerokit RLN supports naive Merkle Tree implementation: when a RLN object is created, a tree of height `N+1` is initialized (including the leaves level) with a total of `2^(N+1)-1` allocated nodes that remain allocated for the whole life of the RLN object, even in case the tree is empty or accumulates less than `2^N` leaves.

For space-efficiency reasons we would like to add support to a Merkle trees implementations that progressively allocates only those nodes which are necessary to prove membership of currently non-empty leaves.

# Acceptance criteria
- [x] Implement Incremental Merkle Tree with APIs compatible with current Merkle Tree implementation (aligned to https://github.com/vacp2p/zerokit/issues/28)
- [ ] ~~No regression in performances with respect to current implementation.~~
- [ ] ~~If regression in performance, evaluate space/time tradeoffs and followup with a better solution.~~

**Comment by staheri14** [comment]
Just for reference and following our conversation in the PM channel, the Merkle tree implementation of the killic lib satisfies the requirement of this issue https://github.com/kilic/rln/blob/master/src/merkle.rs, feel free to use that

**Comment by staheri14** [comment]
Not sure about this last item 
> If regression in performance, evaluate space/time tradeoffs and followup with a better solution.
But if I understand it correctly, this maps to this issue https://github.com/vacp2p/research/issues/109 which I am already working on it and the result of my work will be ultimately integrated into zero-kit.

**Comment by oskarth** [comment]
To make sure I understand correctly, this issue is about porting the incremental MT algorithm already used in kilic.

1) Is this correct and there's nothing else in the scope of this?
- I believe the answer is yes 
2) How confident are we this code will be ultimately used once we've done more analysis in e.g. https://github.com/vacp2p/research/issues/109?
- Assuming same MT approach, my intuition would be fairly
- However long term I could imagine a different representation, in which case this solution would be an interim one
- It seems to me like an incremental MT representation plus possibly additional tweaks discovered would be "good enough" for cross-client test and for smaller user sets, i.e. for foreseeable future
3) Do we want this to be implemented before we switch to Zerokit by default? (after this testnet)
- Intuition says yes, but I'm not familiar enough about details of current perf problems for MT storage

**Comment by oskarth** [comment]
Assuming above is roughly correct, I believe the second two points under acceptance criteria don't have to be done, as we can assume this is done in https://github.com/vacp2p/research/issues/109 at least from an algorithmic POV.

If the script for doing empirical evaluation here is done in nwaku (e.g. to check storage size) then it should be trivial to re-run the basic tests done in that issue also for Zerokit. This means we reduce risk for performance regressions when integrating Zerokit. Please confirm that matches your expectations @staheri14

**Comment by oskarth** [comment]
@staheri14 it'd be great if you could respond to points above first before creating another issue like https://github.com/vacp2p/research/issues/127 - to me that issue just creates more questions. We want to reduce uncertainty, not increase it.

**Comment by staheri14** [comment]
> Assuming above is roughly correct, I believe the second two points under acceptance criteria don't have to be done, as we can assume this is done in https://github.com/vacp2p/research/issues/109 at least from an algorithmic POV.

Right

> If the script for doing empirical evaluation here is done in nwaku (e.g. to check storage size) then it should be trivial to re-run the basic tests done in that issue also for Zerokit.
Yes, the basic empirical test would be replicable in zero kit. However, a part of the storage overhead analysis is focused on the computational complexity of the underlying algorithm, hence the result is applicable regardless of the implementation.

**Comment by staheri14** [comment]
> @staheri14 it'd be great if you could respond to points above first before creating another issue like [vacp2p/research#127](https://github.com/vacp2p/research/issues/127) - to me that issue just creates more questions. We want to reduce uncertainty, not increase it.

The following issue https://github.com/vacp2p/research/issues/127 captures the general performance of the group management in the rln-relay protocol i.e., computation and storage.  But the current issue and https://github.com/vacp2p/research/issues/109 are the tasks within that milestone.
