### ISSUE TITLE
Zerokit generalize API to allow for any Circom based proof

### ISSUE THREAD

**Issue by oskarth** [vacp2p/zerokit#71]
# Problem

Currently we are doing special-purpose APIs for e.g. RLN. It'd be useful to factor out the general parts and allow and Circom-based circuits to be used through Zerokit.

## Context

Obviously not doable for all APIs, but e.g. `prove` and `verify` + general format for inputs seems doable? Especially if it is using JSON or whatever for passing data.

(This doesn't mean we shouldn't also have special purpose APIs that are useful for specific circuits).

## Acceptance criteria

Some way of dealing with with generic Circom circuits (e.g. ones that the library doesn't know about!) to do basic `prove` and `verify` operations.

**Comment by oskarth** [comment]
cc @s1fr0

**Comment by staheri14** [comment]
Sharing some of the takeaways from my call with Oskar:
- we can also have multiple options regarding the _API_:   Rust, C API, or a command-line Interface.
- One incremental step towards this issue is to define a Makefile that encapsulates recurring commands e.g., proof generation and verification. The name of the circom file then can be an argument for the Makefile.

**Comment by staheri14** [comment]
> The way how API were structured aimed to a generic design. There is an
> 
> * `APPWitnessInput` object which collects the witness value that fed the circuit through `prove/generate_app_proof`;
> * `APPProofValues` object which collects the proof values against which the proof is verified through `verify/verify_app_proof`.
>   A bit more context on the rationale is provided in the last paragraph of [Proof verification is true for IDCommitment not in merkle tree? #57 (comment)](https://github.com/vacp2p/zerokit/issues/57#issuecomment-1264287219)
> 
> What can be further abstracted with respect to this issue is probably a handler for the serialization/deserialization of these two which will make the proof/verify API completely abstract and independent from the definition of witness/proof values.

Is there already documentation highlighting that the APIs are generic and reusable for any circuit? if not, I think that would be another step to take

**Comment by tyshko-rostyslav** [comment]
I am not completely sure of the motivation for this issue.
Generalisation of all Circom based circuits seems to be out of scope of our project, and should (if at all), probably be done in `ark-circom`.
If we are talking about implementing new modules and new circuits for our internal usage, it is already simple and generic enough to do it the current way. Thing is that would still need a separate API for each module, and serialisation could be different, so whatever we abstract out of current implementation will surface out when using the new generalised API, so we won't have any benefits here.

**Comment by rymnc** [comment]
Agreed, general format for inputs is not necessarily "safe", and each circuit should have their own api. Closing this issue.
